EXCEL_COLUMNS = {
    "operadora": "Operadora",
    "grupo_demanda": "Grupo Demanda",
    "projeto": "Projeto",
    "status": "Status 1",
    "empresa_responsavel": "Empresa Responsável",
    "ultimo_status": "Último Status",
    "ponto_focal": "Ponto focal responsável",
    "historico_status": "Histórico de Status",
    "imovel": "Imóvel",
    "endereco": "Endereço",
    "cidade": "Cidade",
    "uf": "UF",
    "id": "ID",
    "monitoramento_cpfl": "Monitoramento CPFL",
    "ip_fg40f": "IP FG40F",
    "servico": "Serviço",
    "banda": "Banda",
    "prazo": "Prazo",
    "termo_aceite": "Termo aceite criado em",
    "projeto_cpfl": "Projeto CPFL",
    "planta_cpfl": "Planta CPFL",
    "chamado_faturamento": "CHAMADO FATURAMENTO",
}